### ISSUE TITLE
Resources Not Correctly Embedded?

### ISSUE THREAD

**Issue by ujaeggi** [geomatics-io/BindingListView#1]
When I try to apply a filter I get the following error:
System.Resources.MissingManifestResourceException: 'Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Equin.ApplicationFramework.Properties.Resources.resources" was correctly embedded or linked into assembly "BindingListView" at compile time, or that all the satellite assemblies required are loadable and fully signed.'

Line to apply filter:
` view.ApplyFilter(delegate (Customer customer) { return customer.Balance > 10; });`

My customer class:
```
public class Customer
    {
        public Customer(string name,  int balance)
        {
            Name = name;
            Balance = balance;
        }

        public string Name { get; set; }
        public int Balance { get; set; }
    }
```

Is tried the latest version 1.3.1 from NuGet.

**Comment by christianarielli** [comment]
Thanks for your feedback. This problem wasn't address by the unit tests. Now, everything should be working again. Try version 1.3.2. This version should be available on NuGet in ~30 minutes from now on. Regards, Christian

**Comment by ujaeggi** [comment]
Works. Thank you!
